export enum ResponseCode {
    APPROVED = "00",
    INVALID_AMOUNT = "13",
    INVALID_CARD_NUMBER = "14",
    LUHN_ALGORITHM_FAILED = "15",
    NULL_VALUE = "16",
    INVALID_CARD_NUMBER_LENGTH = "17",
    AMOUNT_EXCEEDED = "31",
    CARD_HOLDER_NOT_FOUND = "32",
    DAILY_TX_LIMIT_EXCEEDED = "33",
    DAILY_TX_SUM_EXCEEDED = "34",
    DAILY_TX_SUM_WILL_BE_EXCEEDED = "35",
    ACCOUNT_NOT_ACTIVE = "36"
}
